export const BLACKLIST_PRODUCT_REQUEST = "BLACKLIST_PRODUCT_REQUEST";
export const BLACKLIST_PRODUCT_SUCCESS = "BLACKLIST_PRODUCT_SUCCESS";
export const BLACKLIST_PRODUCT_FAILURE = "BLACKLIST_PRODUCT_FAILURE";

export const FETCH_BLACKLIST_REQUEST = "FETCH_BLACKLIST_REQUEST";
export const FETCH_BLACKLIST_SUCCESS = "FETCH_BLACKLIST_SUCCESS";
export const FETCH_BLACKLIST_FAILURE = "FETCH_BLACKLIST_FAILURE";