// storeActionTypes.js

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const STORE_REGISTER_REQUEST = 'STORE_REGISTER_REQUEST';
export const STORE_REGISTER_SUCCESS = 'STORE_REGISTER_SUCCESS';
export const STORE_REGISTER_FAIL = 'STORE_REGISTER_FAIL';

export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';


export const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE";


export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAILURE = "UPDATE_STORE_FAILURE";


export const FETCH_STORES_REQUEST = "FETCH_STORES_REQUEST";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILURE = "FETCH_STORES_FAILURE";


// storeConstants.js

export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';



export const FETCH_STORE_PRODUCTS_REQUEST = 'FETCH_STORE_PRODUCTS_REQUEST';
export const FETCH_STORE_PRODUCTS_SUCCESS = 'FETCH_STORE_PRODUCTS_SUCCESS';
export const FETCH_STORE_PRODUCTS_FAILURE = 'FETCH_STORE_PRODUCTS_FAILURE';

export const FETCH_STORE_SALES_REQUEST = 'FETCH_STORE_SALES_REQUEST';
export const FETCH_STORE_SALES_SUCCESS = 'FETCH_STORE_SALES_SUCCESS';
export const FETCH_STORE_SALES_FAILURE = 'FETCH_STORE_SALES_FAILURE';


export const FETCH_STORE_DETAILS_REQUEST = 'FETCH_STORE_DETAILS_REQUEST';
export const FETCH_STORE_DETAILS_SUCCESS = 'FETCH_STORE_DETAILS_SUCCESS';
export const FETCH_STORE_DETAILS_FAILURE = 'FETCH_STORE_DETAILS_FAILURE';



export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAIL = 'WITHDRAW_FAIL';


export const FETCH_BLACKIST_PRODUCTS_REQUEST = 'FETCH_BLACKIST_PRODUCTS_REQUEST';
export const FETCH_BLACKIST_PRODUCTS_SUCCESS = 'FETCH_BLACKIST_PRODUCTS_SUCCESS';
export const FETCH_BLACKIST_PRODUCTS_FAILURE = 'FETCH_BLACKIST_PRODUCTS_FAILURE';



export const SUSPEND_STORE_REQUEST = "SUSPEND_STORE_REQUEST";
export const SUSPEND_STORE_SUCCESS = "SUSPEND_STORE_SUCCESS";
export const SUSPEND_STORE_FAILURE = "SUSPEND_STORE_FAILURE";


export const RECOVER_STORE_REQUEST = "RECOVER_STORE_REQUEST";
export const RECOVER_STORE_SUCCESS = "RECOVER_STORE_SUCCESS";
export const RECOVER_STORE_FAILURE = "RECOVER_STORE_FAILURE";

export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";

