
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';
 export const EMAIL_VERIFY_REQUEST = 'EMAIL_VERIFY_REQUEST';
 export const EMAIL_VERIFY_SUCCESS = 'EMAIL_VERIFY_SUCCESS';
 export const EMAIL_VERIFY_FAIL = 'EMAIL_VERIFY_FAIL'